Update hana-cloud-mission-extend-09.md
sap-tutorials/Tutorials pull request #18205
Opened 2022-03-15 09:29 UTC by whome00

Corresponding changes based on https://github.com/sap-tutorials/Tutorials/issues/18204

2022-03-15 09:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-tutorials/Tutorials?pullRequest=18205) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sap-tutorials/Tutorials?pullRequest=18205) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-tutorials/Tutorials?pullRequest=18205) it.</sub>

2022-03-15 10:16 UTC, MichaelCzcz requested changes
Thank you for making this change. Please also update the tags. The name space "products" is no longer valid. Please replace it with the new name space "software-product".

2022-03-16 15:13 UTC, jmmargo commented
Please make the updates to the tags as Michael recommended previously.

2022-03-21 05:22 UTC, closed without merging

2022-03-21 05:23 UTC, whome00 commented
Have a different pull request with the corresponding changes based on https://github.com/sap-tutorials/Tutorials/issues/18204 and changes to tags