corrected Issue #18297
sap-tutorials/Tutorials pull request #18365
Opened 2022-04-26 07:47 UTC by jzwickel

2022-04-26 07:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-tutorials/Tutorials?pullRequest=18365) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sap-tutorials/Tutorials?pullRequest=18365) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-tutorials/Tutorials?pullRequest=18365) it.</sub>

2022-04-26 13:09 UTC, MichaelCzcz requested changes
Thank you for your pull request. Please address the comment in line 203 and update the tutorial tags. The name space "products" is no longer valid. Please use "software-product" instead.

2022-04-26 13:09 UTC, MichaelCzcz commented on tutorials/hana-cloud-mission-trial-9/hana-cloud-mission-trial-9.md
> +3.	Now that our new user `report` is created, we need to grant the user access to the role `PublicAccessSchema`.
Please don't say "we" and "our" unless you are referring to SAP.
Please change all occurrences

2022-05-02 08:23 UTC, MichaelCzcz commented
@jzwickel Please address the requested changes, otherwise I cannot merge this pull request.

2022-05-02 08:31 UTC, jzwickel commented
@MichaelCzcz your requested changes were independent of the reported issue. So in fact it would have been cleaner to deal with them separately. 
As you know, following the process with Atom is pretty cumbersome and takes considerably time. I will push the changes when I have solved the process issue.
Best,
Jan

2022-05-02 15:23 UTC, merged