data-lake-file-containers-hdlfscli
sap-tutorials/Tutorials pull request #18507
Opened 2022-06-10 20:59 UTC by rnagweka

Some additional changes were done to the existing tutorial so that the content becomes even more better to understand with respect to adding the client.crt and some changes to the hdlfscli commands.

2022-06-10 20:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-tutorials/Tutorials?pullRequest=18507) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sap-tutorials/Tutorials?pullRequest=18507) before we can accept your contribution.<br/><hr/>**RONIT NAGWEKAR** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-tutorials/Tutorials?pullRequest=18507) it.</sub>

2022-06-13 06:12 UTC, MichaelCzcz commented
@rnagweka Please link your Github account to Open Source Portal as described here: https://jam4.sapjam.com/groups/A7NmsKmoG9vVaxizKhdQOk/overview_page/jpJF7KXn5B2tFFQVOQ1Ybm?edit_mode=true

2022-06-13 06:15 UTC, MichaelCzcz requested changes

2022-06-13 06:15 UTC, MichaelCzcz commented on tutorials/data-lake-file-containers-hdlfscli/data-lake-file-containers-hdlfscli.md
>  **Note**: Make sure the certificate fields are not all exactly the same between the Certificate Authority (CA) and client certificates, otherwise it is assumed to be a self-signed cert and the cert v
Please adjust formatting as shown in the style guide. Don't start a note with the label "Note". Please do this for all notes with wrong formatting.
https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtqfqchq21

2022-06-20 06:30 UTC, MichaelCzcz commented
@rnagweka Can you please address the requested changes? Thank you.

2022-06-21 08:16 UTC, MichaelCzcz commented
The notes still have the wrong formatting. Please format them as shown in the style guide. https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtqfqchq21

2022-06-21 22:40 UTC, rnagweka commented
I have pushed the tutorial to production 
Please let me know if it's fine.

2022-06-22 07:06 UTC, MichaelCzcz commented
How to format notes:

Wrong: 
Note: This is a note.

Correct:
>This is a note

2022-07-06 07:53 UTC, MichaelCzcz commented
@rnagweka What's the status?

2022-08-01 05:47 UTC, MichaelCzcz commented
@rnagweka I haven't heard from you in over a month. If you are still interested in this pull request, please reply by the end of this week. Otherwise I will close it.

2022-08-02 16:39 UTC, rnagweka commented
Hey,
 Yes, I have done the necessary changes for the tutorial. Sorry had to replace my laptop in the past month and because of that I didnt have any data saved for this tutorial. Please could you review the changes and let me know

2022-08-03 08:31 UTC, MichaelCzcz commented
Please sign CLA.

2022-08-03 14:00 UTC, MichaelCzcz requested changes
Please address the comments and check for more typos. The spell checker is not perfect and may have missed some.

2022-08-03 17:01 UTC, rnagweka commented on tutorials/data-lake-file-containers-hdlfscli/data-lake-file-containers-hdlfscli.md
> +The HDLFSCLI is included in the HANA Data Lake Client download from the [SAP software center](https://launchpad.support.sap.com/#/softwarecenter/template/products/_APP=00200682500000001943&_EVENT=NEX
Sure, thanks for pointing it out. I will make the changes.

2022-08-03 17:27 UTC, rnagweka commented
I have made the necessary changes to this tutorial. Please have a look. Thanks.

2022-08-04 06:02 UTC, MichaelCzcz commented
Thanks. Please sign CLA and update your Github profile/git settings. 

![image](https://user-images.githubusercontent.com/57144076/182774365-52486c39-c3d5-49d3-84ac-2a4e7ccc818b.png)

2022-08-04 16:45 UTC, rnagweka commented
![image](https://user-images.githubusercontent.com/105741084/182905618-0aae5a54-4339-4f70-9195-272bbb27160b.png)

 I have already signed the CLA a multiple times. Dont know why isnt it reflecting on your end. Let me know what can I do?

2022-08-05 06:12 UTC, merged