Use SOF to Query data from Single Directory
sap-tutorials/Tutorials pull request #18702
Opened 2022-08-09 19:41 UTC by rnagweka

You will learn
 -	How to define the database objects required to query structured data files.
 -	How to add a data source for a single data file and query the output of that file.

2022-08-09 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-tutorials/Tutorials?pullRequest=18702) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/sap-tutorials/Tutorials?pullRequest=18702) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rnagweka<br/>:x: RONIT NAGWEKAR<br/><hr/>**RONIT NAGWEKAR** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-tutorials/Tutorials?pullRequest=18702) it.</sub>

2022-08-29 07:21 UTC, MichaelCzcz commented
@rnagweka Please resolve conflicts. Thank you.

2022-09-13 06:29 UTC, MichaelCzcz commented
@rnagweka Are you still interested in this PR getting merged?

2022-09-13 16:37 UTC, rnagweka commented
HI Michael,

Yes I want this pull request to get merged.

Regards,
Ronit Nagwekar

From: Michael Czadankiewicz ***@***.***>
Sent: September 13, 2022 2:29 AM
To: sap-tutorials/Tutorials ***@***.***>
Cc: Nagwekar, Ronit ***@***.***>; Mention ***@***.***>
Subject: Re: [sap-tutorials/Tutorials] Use SOF to Query data from Single Directory (PR #18702)


@rnagweka<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frnagweka&data=05%7C01%7Cronit.nagwekar%40sap.com%7Cba2044f6a570487accd808da95514701%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637986473560086154%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=loSu0QlRSY2G2EvHEfpCpsoa93LTjHud24GMBFUXPmM%3D&reserved=0> Are you still interested in this PR getting merged?

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsap-tutorials%2FTutorials%2Fpull%2F18702%23issuecomment-1244958279&data=05%7C01%7Cronit.nagwekar%40sap.com%7Cba2044f6a570487accd808da95514701%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637986473560086154%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Na4Bzu69fkXi621haDErYkcGKp9Qgmewp8dPxcBIA8o%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZGXWHCLUFQWKJAA2777G7TV6ANLTANCNFSM56B6SCJQ&data=05%7C01%7Cronit.nagwekar%40sap.com%7Cba2044f6a570487accd808da95514701%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637986473560242407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FAB8gWssmR6WSbyTaWQEjcGDpL7tr%2BLcXGMd8dN5rfk%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-09-26 11:42 UTC, MichaelCzcz commented
@rnagweka Well, then please resolve the conflicts.

2022-10-26 08:09 UTC, MichaelCzcz commented
@rnagweka There is only one conflict that needs to be resolved:
<<<<<<< master
 - A licensed SAP HANA Data Lake instance (non-trial / non-free tier).
=======
 - A licensed SAP HANA data lake instance (non-trial / non-free tier).
>>>>>>> master

2022-10-26 08:17 UTC, MichaelCzcz requested changes

2022-10-26 08:17 UTC, MichaelCzcz commented on tutorials/data-lake-file-containers-hdlfscli/data-lake-file-containers-hdlfscli.md
> +**Note:** You will need this later when you configure authentication for HDL Files.
Please don't start a note with the label "Note". The formatting already makes it a note. 
Please check the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtqfqchq21) for details.

2022-10-26 08:17 UTC, MichaelCzcz commented on tutorials/data-lake-file-containers-hdlfscli/data-lake-file-containers-hdlfscli.md
> +**Note:** The configuration will be placed in the **user's root directory**. It is saved as a JSON file that can be modified in any text editor.
Please don't start a note with the label "Note". The formatting already makes it a note.
Please check the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtqfqchq21) for details.

2022-10-26 08:17 UTC, MichaelCzcz commented on tutorials/data-lake-hdlfs-dbx-connection/data-lake-hdlfs-dbx-connection.md
> +We need to verify whether we have added the right connection of File Container in DBX. We can do that by adding/uploading a file to the File container and checking it in the DBX.
Please don't use the "royal we" when addressing the user. Use "you" instead.
Please check the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtvf24ta2) for details.

2022-10-26 08:17 UTC, MichaelCzcz commented on tutorials/data-lake-sof-multiple-directories/data-lake-sof-multiple-directories.md
> +We will be using the Orders table as a reference.
Please don't use the "royal we" when addressing the user. Use "you" instead.
Please check the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtvf24ta2) for details.

2022-10-26 08:17 UTC, MichaelCzcz commented on tutorials/data-lake-sof-multiple-directories/data-lake-sof-multiple-directories.md
> +Note that the table definition will need to match the expected schema/data types of the columns in the structured file you are trying to query. Login to the SQL console as User1 or HDLADMIN and execu
Please fix grammar (the login, to log in). Who is "I"?

2022-10-26 08:17 UTC, MichaelCzcz commented on tutorials/data-lake-sof-multiple-directories/data-lake-sof-multiple-directories.md
> +Firstly, we create a SCHEMA in files service.
Please don't use the "royal we" when addressing the user. Use "you" instead.
Please check the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtvf24ta2) for details.

2022-10-26 08:17 UTC, MichaelCzcz commented on tutorials/data-lake-sof-multiple-directories/data-lake-sof-multiple-directories.md
> +Next, we create a virtual table. Notice in the SQL below where the remote servers name goes and where the reference to the table in the Files Service goes. Over here, we will be creating an ORDERS VI
Please don't use the "royal we" when addressing the user. Use "you" instead.
Please check the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtvf24ta2) for details.

2022-10-26 08:17 UTC, MichaelCzcz commented on tutorials/data-lake-sof-multiple-directories/data-lake-sof-multiple-directories.md
> +In this case, we will create the folder structure in such a way that for ORDERYEAR=2020, it will query the data for that particular year i.e. 2020. We can also query the data for a particular month f
Please don't use the "royal we" when addressing the user. Use "you" instead.
Please check the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtvf24ta2) for details.

2022-11-03 21:31 UTC, jmmargo commented
There is a conflict with the email address used to open this pull request.  Ronit will try to push these again.

2022-11-03 21:31 UTC, closed without merging