move to prod
sap-tutorials/Tutorials pull request #18966
Opened 2022-10-27 14:48 UTC by pbujnicka

2022-10-28 06:26 UTC, MichaelCzcz requested changes

2022-10-28 06:26 UTC, MichaelCzcz commented on tutorials/spa-create-automation/spa-create-automation.md
> +In this exercise, you will automate the process to read the *sales order* details from an Excel and select the specific sales order details based on the input from the submitted form. To design your
Excel

2022-10-28 06:26 UTC, MichaelCzcz commented on tutorials/spa-create-decision/spa-create-decision.md
> +    > A decision table is a tabular representation of the rule with If and Then header and row columns. If-header columns contain the expressions which are evaluated, and Then-header columns contain
Missing comma before "which"

2022-10-31 12:59 UTC, pbujnicka commented on tutorials/spa-create-automation/spa-create-automation.md
> +In this exercise, you will automate the process to read the *sales order* details from an Excel and select the specific sales order details based on the input from the submitted form. To design your
done

2022-10-31 14:52 UTC, pbujnicka commented on tutorials/spa-create-decision/spa-create-decision.md
> +    > A decision table is a tabular representation of the rule with If and Then header and row columns. If-header columns contain the expressions which are evaluated, and Then-header columns contain
done

2022-10-31 15:52 UTC, merged