Updates to CAP tutorials
sap-tutorials/Tutorials pull request #20753
Opened 2022-11-23 10:17 UTC by slavipande

Files are in the old v1 Tutorial Navigator syntax, which should be still supported, as shared by Joshua.

2022-11-23 12:43 UTC, MichaelCzcz requested changes
These tutorials have severe errors, because you have changed them back to the deprecated v1 parser syntax. I have only pointed out the first issues that I have noticed. You should have received an email with details about the new syntax. I you have not received it, please get in touch with Iwona.

2022-11-23 12:43 UTC, MichaelCzcz commented on tutorials/btp-app-kyma-undeploy-cap-application/btp-app-kyma-undeploy-cap-application.md
> +## Details
Please remove this line!

2022-11-23 12:43 UTC, MichaelCzcz commented on tutorials/btp-app-kyma-undeploy-cap-application/btp-app-kyma-undeploy-cap-application.md
> +### You will learn
This should be: ## You will learn. Also, please move this section above ## Prerequisites

2022-11-23 12:43 UTC, MichaelCzcz commented on tutorials/btp-app-kyma-undeploy-cap-application/btp-app-kyma-undeploy-cap-application.md
> +[ACCORDION-BEGIN [Step 1: ](Undeploy your CAP application from Kyma)]
Wrong Syntax.

2022-11-23 12:43 UTC, MichaelCzcz commented on tutorials/btp-app-kyma-undeploy-cap-application/btp-app-kyma-undeploy-cap-application.md
> +[VALIDATE_1]
Remove this line. Validation is handled by rules.vr only

2022-11-23 12:43 UTC, MichaelCzcz commented on tutorials/btp-app-prepare-dev-environment-cap/btp-app-prepare-dev-environment-cap.md
> +## Details
Remove this line

2022-11-24 10:48 UTC, slavipande commented
> These tutorials have severe errors, because you have changed them back to the deprecated v1 parser syntax. I have only pointed out the first issues that I have noticed. You should have received an email with details about the new syntax. I you have not received it, please get in touch with Iwona.

Hi @MichaelCzcz ,

Looks like there's a misunderstanding in our team's communication with @jmmargo. My colleague @manjuX had checked with Joshua to confirm if the v1 syntax would still be supported. We're authoring our tutorials in MkDocs and have a tool that converts our syntax to v1. We did not update our tool based on this understanding that v1 will still be supported. 
I guess we can follow up on this once Joshua is back from his OOO.

Best regards,
Svetoslav

2022-11-28 13:09 UTC, MichaelCzcz commented
@slavipande I will discuss this with Joshua and get back to you.

2022-11-30 14:34 UTC, jmmargo commented
The v1 parser is still active.  A tutorial may be authored in v1 or v2; we ask that they are not mixed.

Thanks,
Joshua

2022-11-30 14:41 UTC, jmmargo commented
Yes, you may still author in v1 syntax.  Please be sure it is consistent.

-Joshua

From: Svetoslav Pandeliev ***@***.***>
Sent: Thursday, November 24, 2022 3:49 AM
To: sap-tutorials/Tutorials ***@***.***>
Cc: Margo, Joshua ***@***.***>; Mention ***@***.***>
Subject: Re: [sap-tutorials/Tutorials] Updates to CAP tutorials (PR #20753)


These tutorials have severe errors, because you have changed them back to the deprecated v1 parser syntax. I have only pointed out the first issues that I have noticed. You should have received an email with details about the new syntax. I you have not received it, please get in touch with Iwona.

Hi @MichaelCzcz<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMichaelCzcz&data=05%7C01%7Cjoshua.margo%40sap.com%7C469af564b25e49da085208dace0974e8%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638048837269437298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fi0LMrcPZmn8hBol15m3JYQL%2FfVlhymffV9%2BolwnbTw%3D&reserved=0> ,

Looks like there's a misunderstanding in our team's communication with @jmmargo<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjmmargo&data=05%7C01%7Cjoshua.margo%40sap.com%7C469af564b25e49da085208dace0974e8%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638048837269437298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=COb1RpA58%2FKyuVcAtCpgKMhnPtokFJHBrFBe%2F52XD9M%3D&reserved=0>. My colleague @manjuX<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FmanjuX&data=05%7C01%7Cjoshua.margo%40sap.com%7C469af564b25e49da085208dace0974e8%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638048837269437298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CWh%2Bobd8PsruCWspiPkTPO8c%2FuHQZCwtANlZzuwfFdU%3D&reserved=0> had checked with Joshua to confirm if the v1 syntax would still be supported. We're authoring our tutorials in MkDocs and have a tool that converts our syntax to v1. We did not update our tool based on this understanding that v1 will still be supported.
I guess we can follow up on this once Joshua is back from his OOO.

Best regards,
Svetoslav

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsap-tutorials%2FTutorials%2Fpull%2F20753%23issuecomment-1326276922&data=05%7C01%7Cjoshua.margo%40sap.com%7C469af564b25e49da085208dace0974e8%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638048837269437298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3IpSv28mOZTbf4q50hllg7HzIXZUNh7OS6Upf60nVZk%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXMAAX2DNAGT3WI5U4VIDLLWJ5BYVANCNFSM6AAAAAASIZE3GE&data=05%7C01%7Cjoshua.margo%40sap.com%7C469af564b25e49da085208dace0974e8%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638048837269437298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hqy9X1V6PR6XxTxZ%2Flp0N7xl0GHlU9FQHnrcKeVUH0E%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-11-30 15:57 UTC, merged