Push Tutorial to Production
sap-tutorials/Tutorials pull request #20770
Opened 2022-11-30 15:25 UTC by Madeline-Schaefer

2022-11-30 15:55 UTC, MichaelCzcz requested changes

2022-11-30 15:55 UTC, MichaelCzcz commented on tutorials/private-link-aws/private-link-aws.md
> + When creating the Endpoint Service, make sure you allowlist the SAP BTP CF AWS Account IDs as described in [Only allow requests from SAP BTP CF's AWS account](https://help.sap.com/docs/PRIVATE_LINK/
This should be a list item

2022-11-30 15:55 UTC, MichaelCzcz commented on tutorials/private-link-aws/private-link-aws.md
> +  - How to create an SAP Private Link instance to connect to your AWS Private Link Service using Cloud Foundry CLI.
Please remove the "." from all lines in this section.

2022-11-30 15:55 UTC, MichaelCzcz commented on tutorials/private-link-aws/private-link-aws.md
> +Upon the creation of a binding between a CF application and a Private Link Service instance, SAP Private Link Service creates a space-scoped [Cloud Foundry application security group](https://docs.cl
Please fix typo (hat -> that)

2022-11-30 15:55 UTC, MichaelCzcz commented on tutorials/private-link-aws/private-link-aws.md
> +[DONE]
Please remove this line.

2022-11-30 15:55 UTC, MichaelCzcz commented on tutorials/private-link-aws/private-link-aws.md
> +[ACCORDION-END]
Please remove this line.

2022-12-02 07:10 UTC, MichaelCzcz commented
Please resolve conflicts. To avoid conflicts, please always do a fetch+pull for your fork before pushing to production.

2022-12-05 23:12 UTC, jmmargo commented
Thank you for making the revisions Madeline.  I did notice that this tutorial does not have a validation.  It is best practice to add at least one validation (knowledge check) to a tutorial.  I will merge this one, but I do recommend adding one in.

2022-12-05 23:14 UTC, merged