changes
sap-tutorials/Tutorials pull request #22743
Opened 2023-01-18 23:36 UTC by celineaudinsap

2023-01-18 23:52 UTC, celineaudinsap reviewed
Added important note

2023-01-18 23:53 UTC, celineaudinsap reviewed
important note

2023-01-19 12:22 UTC, MichaelCzcz requested changes
I am not sure about the primary tag software-product>sap-build and I could not find it in IMS.
@jmmargo can you confirm that this tag does exist?

2023-01-19 12:22 UTC, MichaelCzcz commented on tutorials/irpa-setup-1-booster-subscription/irpa-setup-1-booster-subscription.md
> +> **IMPORTANT:** Note: [The SAP BTP trial offering will no longer be available as of January 31st, 2023](https://blogs.sap.com/2023/01/09/trial-accounts-retirement-of-sap-intelligent-rpa-end-of-janua
Please remove the word "Note".

2023-01-19 14:04 UTC, closed without merging