Master
sap-tutorials/Tutorials pull request #22767
Opened 2023-01-26 09:28 UTC by julieplummer20

2023-01-26 09:58 UTC, MichaelCzcz requested changes

2023-01-26 09:58 UTC, MichaelCzcz commented on tutorials/abap-environment-external-api/abap-environment-external-api.md
> +This tutorial was written for SAP BTP ABAP Environment. However, you should also be able to use it in SAP S/4HANA Cloud Environment in the same way.
I would format this as a note.

2023-01-26 09:58 UTC, MichaelCzcz commented on tutorials/abap-environment-external-api/abap-environment-external-api.md
> +If you are using JSON, skip this step.
I would format this as a note.

2023-01-26 09:58 UTC, MichaelCzcz commented on tutorials/abap-environment-external-api/abap-environment-external-api.md
> +To be able to access the external service, you must:
If the order of these steps is relevant, please use an ordered list.

2023-01-26 09:58 UTC, MichaelCzcz commented on tutorials/abap-environment-external-api/abap-environment-external-api.md
> +To be able to access the external service, you must:
If the order of these steps is relevant, please use an ordered list.

2023-01-26 14:51 UTC, jmmargo commented
Julie, in step 10, there should be a line break between the first line of text and the first image.  They are currently appearing side-by-side.  You can add an empty <div></div> tag in between if a line break itself does not work.

2023-01-31 13:33 UTC, julieplummer20 commented
Done

2023-02-01 10:32 UTC, julieplummer20 reviewed
Fixed link; fixed ordered lists

2023-02-01 14:31 UTC, merged