Update prerequisites
sap-tutorials/Tutorials pull request #22899
Opened 2023-03-03 13:02 UTC by mervey45

-

2023-03-03 13:34 UTC, MichaelCzcz requested changes

2023-03-03 13:34 UTC, MichaelCzcz commented on tutorials/abap-environment-deploy-cf-production/abap-environment-deploy-cf-production.md
> +      **HINT:** If you can't find your service name, you can press **CTRL + space** to search for it.
Please be consistent with upper/lower case within your tutorials.

2023-03-03 13:34 UTC, MichaelCzcz commented on tutorials/abap-s4hanacloud-procurement-purchasereq-shop/abap-s4hanacloud-procurement-purchasereq-shop.md
> +     **Please note**: Error Invalid XML format.
Please use formatting for notes.

2023-03-03 13:53 UTC, mervey45 commented
@MichaelCzcz I updated the hint sections

2023-03-06 07:08 UTC, MichaelCzcz commented
@mervey45 Please resolve conflicts

2023-03-06 16:49 UTC, jmmargo commented
Merve, If I understand correctly, Michael would prefer you use the ">" syntax for notes instead of saying "Please note."  Anyplace where it is important to note something, the best practice is to use ">" followed by the text.  You do not need words like "Note" or "Please note" or "Hint" as the text will be visually offset with the ">" function.

2023-03-07 11:50 UTC, mervey45 commented
@jmmargo I changed the hint to >

2023-03-07 15:58 UTC, jmmargo commented
Merve, thank you for adding the note syntax; however, as there is a space between the ">" and the text that follows, it is not rendering correctly.  You can double check this in QA Blue.  There should not be a space between the ">" and the following text.

2023-03-07 16:03 UTC, mervey45 commented
@jmmargo I deleted the space between the text and >

2023-03-08 16:10 UTC, jmmargo commented
Thank you for rmaking the changes.

2023-03-08 16:11 UTC, merged