Update Luigi tutorials
sap-tutorials/Tutorials pull request #22922
Opened 2023-03-13 09:06 UTC by alexandra-simeonova

NOTE: This PR is not ready for merge. It requires some more changes from the development team. When it is ready, the draft status will be removed.

Update Luigi tutorial sample: 

- Remove outdated dependencies
- Update to React 18
- Add new example for the Luigi tutorials at https://developers.sap.com/group.luigi-app.html

2023-03-13 09:20 UTC, ndricimrr commented on tutorials/luigi-app-basic-setup/luigi-app-basic-setup.md
> +    curl https://raw.githubusercontent.com/SAP/luigi/main/core/examples/luigi-example-react/src/views/sample1.js > src/views/sample2.js
```suggestion
    curl https://raw.githubusercontent.com/SAP/luigi/main/core/examples/luigi-example-react/src/views/sample1.js > src/views/sample2.js
    curl https://raw.githubusercontent.com/SAP/luigi/main/core/examples/luigi-example-react/public/index.html > public/index.html
    curl https://github.com/SAP/luigi/blob/main/core/examples/luigi-example-react/public/sampleapp.html > public/sampleapp.html
```

2023-03-13 09:34 UTC, ndricimrr commented on tutorials/luigi-app-basic-setup/luigi-app-basic-setup.md
> +    mkdir src/assets
```suggestion
    mkdir -p src/views
    mkdir -p src/assets
```

2023-03-13 09:42 UTC, ndricimrr commented on tutorials/luigi-app-basic-setup/luigi-app-basic-setup.md
> +    mkdir -p src/assets
```suggestion
    mkdir -p src/assets
    mkdir -p public
```

2023-03-13 12:11 UTC, MichaelCzcz requested changes
Please address comments and resolve conflicts. 
Always pull from Github before pushing to prevent future conflicts!

2023-03-13 12:11 UTC, MichaelCzcz commented on tutorials/luigi-app-react/luigi-app-react.md
> +2. **Note** the following line. By default our `webpack-dev-server` will redirect all requests to `index.html` which is our app's main entry point where the Luigi Core library is injected.
Don't use the label "Note" and use the correct formatting for notes as described in the Tutorials style guide.
Also, there is a comma missing feore "which".

2023-03-13 12:11 UTC, MichaelCzcz commented on tutorials/luigi-app-react/luigi-app-react.md
> +   However since the microfrontends are also built in the same environemnt, we will need to host the root React microfrontend app inside another file, which we have named `sampleapp.html`. A similar
Use You and not the royal We.(unless, in rare cases, you are referring to SAP).

2023-03-13 12:11 UTC, MichaelCzcz commented on tutorials/luigi-app-basic-setup/luigi-app-basic-setup.md
>      ![UI5 Terminal](ui5-yo.png)
Add a border to this image and use parser v2 syntax!

2023-03-13 14:41 UTC, alexandra-simeonova commented on tutorials/luigi-app-react/luigi-app-react.md
> +        <Route path="/products" element={<Product localeDict={dict[currentLocale]} />} />
```suggestion
        <Route path="/products" element={<Products localeDict={dict[currentLocale]} />} />
```

2023-03-14 12:57 UTC, ndricimrr reviewed
Some last comments

2023-03-14 12:57 UTC, ndricimrr commented on tutorials/luigi-app-localization-ui5/luigi-app-localization-ui5.md
>      Quantity = Anzahl
```suggestion
    ModalText = Produktdetails
    Quantity = Anzahl
    appTitle = ui5
    appDescription = Deutsch
```

2023-03-14 12:57 UTC, ndricimrr commented on tutorials/luigi-app-localization-ui5/luigi-app-localization-ui5.md
>      ModalText = Product Details
```suggestion
    ModalText = Product Details
    appTitle = ui5
    appDescription = English
```

2023-03-14 12:57 UTC, ndricimrr commented on tutorials/luigi-app-localization-ui5/luigi-app-localization-ui5.md
> +1. Edit the ​`ui5-mf/webapp/view/Order.view.xml` ​file by marking the translated target text. Replace line 17 with:
```suggestion
1. Edit the ​`ui5-mf/webapp/view/Main.view.xml` ​file by marking the translated target text. Replace `<ObjectAttribute>` tag with:
```

2023-03-14 13:15 UTC, alexandra-simeonova commented
Closing due to branch created wrongly before pulling latest state

2023-03-14 13:15 UTC, closed without merging