Additions due to new features for dbx extension
sap-tutorials/Tutorials pull request #22967
Opened 2023-03-30 17:11 UTC by chaitya-patel

Added additional step and updated for new features

2023-03-31 08:44 UTC, MichaelCzcz requested changes

2023-03-31 08:44 UTC, MichaelCzcz commented on tutorials/hana-dbx-extension/hana-dbx-extension.md
> +3. Visual Studio Code also has built-in functionality that allows you to split editors which can be very useful to customize your workspace. For example, if you are working on multiple tasks, or need
Missing comma before which

2023-03-31 08:44 UTC, MichaelCzcz commented on tutorials/hana-dbx-extension/hana-dbx-extension.md
> +4. Additionally, Visual Studio Code has other features to help organize your workspace. The icons in the top right corners allow you to toggle (hide/show) different parts of the workspace which you c
Missing comma before which

2023-04-03 17:37 UTC, chaitya-patel commented on tutorials/hana-dbx-extension/hana-dbx-extension.md
> +4. Additionally, Visual Studio Code has other features to help organize your workspace. The icons in the top right corners allow you to toggle (hide/show) different parts of the workspace which you c
done!

2023-04-03 17:37 UTC, chaitya-patel commented on tutorials/hana-dbx-extension/hana-dbx-extension.md
> +3. Visual Studio Code also has built-in functionality that allows you to split editors which can be very useful to customize your workspace. For example, if you are working on multiple tasks, or need
done!

2023-04-05 16:23 UTC, merged