AI Launchpad New tutorial
sap-tutorials/Tutorials pull request #7333
Opened 2021-12-20 06:03 UTC by dhrubpaul

2022-01-05 10:41 UTC, MichaelCzcz requested changes
Thank you for submitting your PR.
I have found some issues and commented on them. I didn't proofread the whole text, so there may be more issues. Please check your text and fix any errors, that you find. The most common one is missing articles (a/the).

2022-01-05 10:41 UTC, MichaelCzcz commented on tutorials/ai-launchpad-producer/ai-launchpad-producer.md
> +    Once your execution status changes to `COMPLETED`, it will generate **Output Artifact** that is, model for text classification.
This sentence looks odd. I think that's because of missing articles and/or words.

2022-01-05 10:41 UTC, MichaelCzcz commented on tutorials/ai-launchpad-producer/ai-launchpad-producer.md
> +Take a note for your generated Output Artifact's (model) ID. You can always visit the execution details page to get this.
"Take a note **of** your generated..."?

2022-01-05 10:41 UTC, MichaelCzcz commented on tutorials/ai-launchpad-producer/ai-launchpad-producer.md
> +4. Identify your model row by in the **Available Artifacts** pane using the unique ID. Select the drop-down next to it and check `text-data`.
I think that "by" should come directly before "using".

2022-01-05 10:41 UTC, MichaelCzcz commented on tutorials/ai-launchpad-producer/ai-launchpad-producer.md
> +You will see the overview of your configuration. The configuration ID is uniquely identifies your configuration.
Missing "and"?

2022-01-05 10:41 UTC, MichaelCzcz commented on tutorials/ai-launchpad-producer/ai-launchpad-producer.md
> +> A deployment refers to the serving/ hosting your model. For this tutorial, the runtime is SAP AI Core, so it will generate a REST endpoint using which you can classify text as `compliment` or `comp
"...so it will generate a REST endpoint using which you can..." - There is something wrong here.

2022-01-07 06:08 UTC, dhrubpaul commented
@MichaelCzcz ,we have made the requested changes.
Please can you validate

2022-01-07 07:38 UTC, MichaelCzcz requested changes
There are still some issues that you did not address. Please read the comments.

2022-01-07 07:38 UTC, MichaelCzcz commented on tutorials/ai-launchpad-producer/ai-launchpad-producer.md
> +You will see the overview of your configuration. The configuration ID is uniquely identifies your configuration.
Please address this issue.
"The configuration ID is uniquely identifies your configuration." is grammatically incorrect. Either add "and" between "uniquely" and "identifies", and change "uniquely" into "unique" or remove the "is".

2022-01-10 08:15 UTC, dhrubpaul commented
@MichaelCzcz ,kindly merge the changes.

2022-01-10 11:12 UTC, merged