Automatic commit: Move 'conversational-ai-sdk-ios-integrate-sampleapp…
sap-tutorials/Tutorials pull request #7358
Opened 2021-12-28 22:35 UTC by MarcoEidinger

…' from QA to Production

2022-01-03 10:12 UTC, MichaelCzcz requested changes
Hello Marco,

thanks for creating a new tutorial. The content is looking good, except for some minor formatting issues. Some screenshots need borders to increase visibility.

2022-01-03 10:12 UTC, MichaelCzcz commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![ODataContainers View](SampleAppODataContainers.png)
Add border.

2022-01-03 10:12 UTC, MichaelCzcz commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![Collections View](SampleAppCollectionsModifiedRightBarButtonItem.png)
Add border.

2022-01-04 00:19 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> + - You have created a SAP Conversational AI chatbot, for example, as described in the tutorial [Build Your First Chatbot with SAP Conversational AI](https://bit.ly/3srXE1F).
done

2022-01-04 00:19 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![Add SAP Conversational AI Mobile SDK channel](./connect-primaryChannel-mobilesdk-add.png)
done

2022-01-04 00:19 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![Add SAP Conversational AI Mobile SDK channel](./connect-primaryChannel-mobilesdk-create.png)
done

2022-01-04 00:19 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    !["Generate OAuth client"](./connect-settings-oauthclient-generate.png)
done

2022-01-04 00:19 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![Generated OAuth client](./connect-settings-oauthclient-generated.png)
done

2022-01-04 00:19 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    !["Navigate to Mobile Connectivity feature"](./ms-features.png)
done

2022-01-04 00:19 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![Create a new destination](./ms-destination-create.png)
done

2022-01-04 00:19 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![Ping the target system to verify that destination works](./ms-destination-created_test.png)
done

2022-01-04 00:20 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![Add Package](./xcode_addPackage.png)
done

2022-01-04 00:20 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![ODataContainers View](SampleAppODataContainers.png)
done

2022-01-04 00:20 UTC, MarcoEidinger commented on tutorials/conversational-ai-sdk-ios-integrate-sampleapp/conversational-ai-sdk-ios-integrate-sampleapp.md
> +    ![Collections View](SampleAppCollectionsModifiedRightBarButtonItem.png)
done

2022-01-04 00:21 UTC, MarcoEidinger commented
> Hello Marco,
> 
> thanks for creating a new tutorial. The content is looking good, except for some minor formatting issues. Some screenshots need borders to increase visibility.

Thanks Michael for the feedback. I applied the suggested changed :)

2022-01-04 07:44 UTC, MichaelCzcz commented
It seems that you did not push the requested changes.

2022-01-04 07:45 UTC, MichaelCzcz requested changes
It seems that you did not push the requested changes.

2022-01-04 13:41 UTC, MarcoEidinger commented
@MichaelCzcz I did with https://github.com/sap-tutorials/Tutorials/pull/7358/commits/6d91f1e480892f964e3925a37e5b7677758bb83f

2022-01-04 13:53 UTC, MichaelCzcz commented
> @MichaelCzcz I did with [6d91f1e](https://github.com/sap-tutorials/Tutorials/commit/6d91f1e480892f964e3925a37e5b7677758bb83f)

No, you didn't. That commit only contains two changes, none of them is adding a border to a screenshot.

![image](https://user-images.githubusercontent.com/57144076/148069134-857f4651-8a18-4f63-a072-6462c199e300.png)

2022-01-04 13:54 UTC, MichaelCzcz requested changes
Please address the requested changes.
You can find information on how to add borders to images in the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtvf3pb64).

2022-01-04 14:25 UTC, MarcoEidinger commented
@MichaelCzcz i previously committed the image files with a border. I wasn’t aware of the style guide, thanks for sharing! So instead of actually changing the images it is possible to add a border in markdown??? (using the !! encoding within the MD file)

2022-01-04 14:36 UTC, MarcoEidinger commented
I added borders to images through markdown encoding !! with commit https://github.com/sap-tutorials/Tutorials/pull/7358/commits/bb5a2b15b89f1417124c26fc858a9bb9b729939c

2022-01-04 14:56 UTC, MichaelCzcz requested changes
I can see the changes in the code now. I am sorry to ask you to make more changes, but your screenshots are to big. So, the borders don't show.
according to the style guide the maximum size 1200x500px. Except for the screenshots taken from your mobile device, all exceed that size.
Please reduce the size of your screenshots and check if the borders are visible in the tutorial.
You can do this here: https://developers-qa.sap.com/tutorials/conversational-ai-sdk-ios-integrate-sampleapp.html
When you replace images, you also have to make a small change to the md-file. Adding a space somewhere is enough. Otherwise the new images will not be displayed.

2022-01-04 16:11 UTC, MarcoEidinger commented
@MichaelCzcz borders are shown in preview 
<img width="1987" alt="Screen Shot 2022-01-04 at 8 09 44 AM" src="https://user-images.githubusercontent.com/4176826/148088610-d09a52ff-c17d-4c39-9f56-405e78d70344.png"> but if you check https://developers-qa.sap.com/tutorials/conversational-ai-sdk-ios-integrate-sampleapp.html then you won't find my changes as I did not double-maintain them in Tutorials-Contributions yet. My amendments were done for this PR only.

Ok, if screen shots have to have a maximum size then I will reduce the size

2022-01-04 16:42 UTC, MarcoEidinger commented
@MichaelCzcz I checked but resizing the images would lead to significant quality loss. I don't want to retake all screenshots. I'd like to appeal to get this PR merged as-is

2022-01-04 19:51 UTC, MarcoEidinger commented
Images were resized to be smaller or equal 1200 width. I copied the changes to QA as well

<img width="1396" alt="Screen Shot 2022-01-04 at 11 50 24 AM" src="https://user-images.githubusercontent.com/4176826/148115623-84f8ff7b-d593-459b-9258-74d7cd3160c6.png">

2022-01-05 08:21 UTC, merged